config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root 'home#index'

    resources :books
    resources :lists

    get '/lists/:id/subscribe', to: 'subscriptions#create', as: 'subscription'
    get '/subscriptions', to: 'subscriptions#index', as: 'subscriptions'
    delete '/subscriptions/:id', to: 'subscriptions#destroy', as: 'destroy_subscription'
    # post '/lists/:id', to: 'subscriptions#create', as: 'subscription'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin_role?
        can :manage, :all
      elsif user.curator_role?
        can :manage, :all
      else
        can :read, :all
      end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
      has_many :selections, dependent: :destroy
      has_many :lists, through: :selections
end

app/models/list.rb
class List < ApplicationRecord
    has_many :selections, dependent: :destroy
    has_many :books, through: :selections

    has_many :subscriptions, dependent: :destroy
    has_many :users, through: :subscriptions
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :list
  belongs_to :book
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :subscriptions
  has_many :lists, through: :subscriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
      lists_path
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    load_and_authorize_resource
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    skip_before_action :authenticate_user!, :only => [:index]

    def index
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    load_and_authorize_resource

    def index
        @lists = List.all
    end

    def show
        @list = List.find_by_id(params[:id])
    end

    def new
        @user = current_user
        @list = List.new
    end

    def create
        @user = current_user
        @list = @user.lists.build(list_params)
        if @list.save
            redirect_to @list
        else
            render 'new'
        end
    end

    def edit
        @user = current_user
        @list = List.find_by_id(params[:id])
    end

    def update
        @list = List.find_by_id(params[:id])
        @list.update(list_params)
        redirect_to @list
    end

    def destroy
        @user = current_user
        List.find(params[:id]).destroy
        redirect_to lists_path
    end

    private
    def list_params
        params.require(:list).permit(:title, :description, :price, :organization, :organization_description, :organization_url, :image_url)
    end

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
    def create
        @user = current_user
        @list = List.find_by_id(params[:id])
        Subscription.create(user_id: @user.id, list_id: @list.id)
        redirect_to lists_path
    end

    def index
        @user = current_user
        @subscription = @user.subscriptions.all
    end

    def destroy
        @user = current_user
        Subscription.find(params[:id]).destroy
        redirect_to subscriptions_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/index.html.erb
<div class= "banner">
    <h1>Dewey List</h1>
    <h2>Read for a Cause</h2>
</div>

<p class="footer">Kathryn Wood | 2017</p>

app/views/layouts/_nav.html.erb
<nav>
    <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo center"><img src="http://i.imgur.com/NLDxFnM.png" alt="Dewey List Logo"></a>
        <a href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="material-icons">menu</i>
        </a>
        <ul class="right hide-on-med-and-down">
            <% if user_signed_in? %>
            <li>
                <a href="<%= lists_path %>">Lists</a>
            </li>
            <li>
                <a href="<%= subscriptions_path %>">Subscriptions</a>
            </li>
            <li>
                <a href="<%= edit_user_registration_path %>">Edit Profile</a>
            </li>
        <% else %>
            <li>
                <a href="<%= new_user_registration_path %>">Sign Up</a>
            </li>
            <li>
                <a href="<%= new_user_session_path %>">Login</a>
            </li>
            <!-- <li><a href="<%= lists_path %>">Lists</a></li> -->
            <% end %>
        </ul>

        <ul class="side-nav" id="mobile-demo">
            <% if user_signed_in? %>
            <li>
                <a href="<%= lists_path %>">Lists</a>
            </li>
            <li>
                <a href="<%= subscriptions_path %>">Subscriptions</a>
            </li>
            <li>
                <a href="<%= edit_user_registration_path %>">Edit Profile</a>
            </li>
        <% else %>
            <li>
                <a href="<%= new_user_registration_path %>">Sign Up</a>
            </li>
            <li>
                <a href="<%= new_user_session_path %>">Login</a>
            </li>
            <!-- <li><a href="<%= lists_path %>">Lists</a></li> -->
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Dewey List</title>
        <%= favicon_link_tag "deweylist_favicon.png" %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <%= csrf_meta_tags %>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Pacifico|Roboto+Condensed" rel="stylesheet">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    </head>

    <body>

        <%= render 'layouts/nav' %>

        <% unless flash.empty? %>
        <script type="text/javascript">
            <% flash.each do |f| %>
            <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
            toastr['<%= type %>']('<%= f[1] %>');
            <% end %>
        </script>
        <% end %>

        <%= yield %>

        <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: "right btn") %>
        <% end %>

        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>

    </body>
</html>

app/views/lists/edit.html.erb
<div class="container">

<h1>Edit Book List</h1>

<%= form_for @list do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :organization %>
    <%= f.text_field :organization %>

    <%= f.label :organization_description %>
    <%= f.text_area :organization_description %>

    <%= f.label :organization_url %>
    <%= f.text_field :organization_url %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.submit %>

<% end %>

</div>

app/views/lists/index.html.erb
<div class="container">
    <h1>Book Lists</h1>

    <div class="row">
        <% @lists.each do |list| %>
            <div class="col s12 m6 l4 list-list">
                <h2><%= link_to list.title, list_path(list) %></h2>
                <h3><%= list.organization %></h3>
                <p><%= list.description %></p>
            </div>
        <% end %>
    </div>

    <% if can? :manage, User %>
        <p><%= link_to "Create New List", new_list_path, class: "waves-effect waves-light btn right" %></p>
    <% end %>

</div>

app/views/lists/new.html.erb
<div class="container">

<h1>New Book List</h1>

<%= form_for @list do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :organization %>
    <%= f.text_field :organization %>

    <%= f.label :organization_description %>
    <%= f.text_area :organization_description %>

    <%= f.label :organization_url %>
    <%= f.text_field :organization_url %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.submit %>


<% end %>

</div>

app/views/lists/show.html.erb
<div class="container">
    <h1><%= @list.title %></h1>

    <%= link_to "Subscribe", subscription_path(@list.id), class: "waves-effect waves-light btn right" %>

    <h2>You'll love this list if...</h2>
    <p><%= @list.description %></p>

    <h2>Benefits
        <%= @list.organization %></h2>
    <p><%= @list.organization_description %></p>
    <p>You can find more information here:
        <%= link_to @list.organization, @list.organization_url %></p>

    <h2>Price per Quarter: $<%= @list.price %></h2>

    <h2>Books</h2>

    <div class="row">
        <% @list.books.each do |book| %>
        <div class="col s12 m6 l4">
            <img src= "<%= book.image_url %>" class= "library">
        </div>
        <% end %>
    </div>

    <% if can? :manage, User %>
    <%= link_to "Edit List", edit_list_path(@list.id), class: "btn right" %>
    <%= link_to "Delete List", list_path(@list.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn right" %>
    <% end %>
</div>

app/views/subscriptions/index.html.erb
<div class= "container">
    <h1>Your Subscriptions</h1>

    <ul>
        <% @subscription.each do |subscription| %>
            <li>
                <h3><%= subscription.list.title %></h3>
                <%= link_to "Unsubscribe", destroy_subscription_path(subscription.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn right" %>
            </li>
          </br>
        <% end %>
    </ul>

</div>